/*
 * Symbols for Silkscreen 32 px: yen, almost-equal, square, triangle.
 * Generated by _research/gen_symbols.py - do not edit by hand.
 * Metrics copied from dsb_32 so it can serve as that font's fallback.
 */

#include "lvgl.h"

#ifndef DSY_32
#define DSY_32 1
#endif

#if DSY_32

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+2248 */
    0xf,0xf0,0xf,0xf0,0x30,0xc,0x30,0xc,0x0,0x0,0x0,0x0,0xf,0xf0,
    0xf,0xf0,0x30,0xc,0x30,0xc,
    /* U+25A0 */
    0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
    0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
    0xff,0xff,0xff,0xff,
    /* U+25B6 */
    0xc0,0x0,0xc0,0x0,0xf0,0x0,0xf0,0x0,0xfc,0x0,0xfc,0x0,0xff,0x0,
    0xff,0x0,0xff,0xc0,0xff,0xc0,0xff,0xf0,0xff,0xf0,0xff,0xfc,0xff,0xfc,
    0xff,0xf0,0xff,0xf0,0xff,0xc0,0xff,0xc0,0xff,0x0,0xff,0x0,0xfc,0x0,
    0xfc,0x0,0xf0,0x0,0xf0,0x0,0xc0,0x0,0xc0,0x0,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 256, .box_w = 16, .box_h = 10, .ofs_x = 0, .ofs_y = -5},
    {.bitmap_index = 20, .adv_w = 256, .box_w = 16, .box_h = 16, .ofs_x = 0, .ofs_y = -11},
    {.bitmap_index = 52, .adv_w = 256, .box_w = 16, .box_h = 26, .ofs_x = 0, .ofs_y = -21},
};

static const uint16_t unicode_list_0[] = {
    0,856,878,
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 8776, .range_length = 879, .glyph_id_start = 1,
        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL,
        .list_length = 3, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY,
    },
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL, .kern_scale = 0, .cmap_num = 1, .bpp = 1,
    .kern_classes = 0, .bitmap_format = 0, .stride = 0,
};

const lv_font_t dsy_32 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 36,
    .base_line = 4,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -2,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL,
};

#endif
