#pragma once

#include "lvgl.h"

// ---------------------------------------------------------------------------
// Proportional Silkscreen Bold faces, generated by _research/gen_dsb.py.
//
// These replaced an earlier monospace family built from the same TTF: a fixed
// advance made every character as wide as "W", so the design's 9 px text rendered
// 25-75% too wide. Silkscreen is proportional in the browser and these faces match
// that, which is what lets the design's own font sizes be used.
//
// Sizes were chosen with _research/solve_sizes.py: for each string it picks the
// largest face that still fits the width the design renders that string at.
//
//   dsb_8    status telemetry, runway, basis and burn lines
//   dsb_9    brand, funds caption
//   dsb_10   token equivalent and yen sign
//   dsb_11   NEXT line
//   dsb_20   balance figures
//   dsb_36   PEAK / TROUGH
//
// Every face also carries the yen sign, "almost equal to", the black square and
// the right-pointing triangle, which Silkscreen itself lacks.
// ---------------------------------------------------------------------------

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t dsr_12;
extern const lv_font_t dsr_14;
extern const lv_font_t dsr_18;
extern const lv_font_t dsr_32;
extern const lv_font_t dsr_44;

// Symbols-only faces carrying yen, almost-equal, black square and triangle.
// Never referenced directly: fonts() chains each as the *fallback* of the matching
// text face, which is how LVGL resolves a glyph the text face does not have.
extern const lv_font_t dsy_12;
extern const lv_font_t dsy_14;
extern const lv_font_t dsy_18;
extern const lv_font_t dsy_32;
extern const lv_font_t dsy_44;

// LVGL's built-in data font, used only by the raw bring-up self test.
extern const lv_font_t lv_font_montserrat_14;

// Runtime copies of the text faces with their symbol fallback attached.
// LVGL's own font structs are const, so the chain needs its own copies.
struct dsb_fonts {
    const lv_font_t *body;     // dsb_9  -> dsy_9
    const lv_font_t *small;    // dsb_8  -> dsy_8
    const lv_font_t *token;    // dsb_10 -> dsy_10
    const lv_font_t *balance;  // dsb_20 -> dsy_20
    const lv_font_t *state;    // dsb_36 -> dsy_36
    const lv_font_t *next;     // dsb_11 -> dsy_11
};

// Attach the fallbacks. Call once before ui_init().
void ui_fonts_init();

// The chained faces, valid after ui_fonts_init().
const struct dsb_fonts *ui_fonts();

#ifdef __cplusplus
}
#endif
